{"Action":"POST","ErrorCode":500,"ErrorMessage":"","URL":"http://cy2caut01:5000/api/v1/testrun","Body":"{\"Id\":0,\"Environment\":\"QA A\",\"FrameworkVersion\":\"1.0.1.9\",\"FkClientId\":3,\"User\":\"rvastrad\",\"GUID\":\"b6975118_047d_47c8_bf0f_b2add4c8750c\",\"StartTime\":\"2020-02-11T10:58:28.2451894-06:00\",\"JiraKeys\":[]}","Message":"Exception of type 'Brierley.TestAutomation.Core.Reporting.RestReportingException' was thrown.","Data":{},"InnerException":null,"StackTrace":"   at Brierley.TestAutomation.Core.Reporting.RestReport.<ExecuteRequestAsync>d__13.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Brierley.TestAutomation.Core.Reporting.RestReport.<CreateTestRunAsync>d__4.MoveNext()","HelpLink":null,"Source":"Brierley.TestAutomation.Core.Reporting","HResult":-2146233088}